container:
    image: rust:latest

test_task:
    cargo_cache:
        folder: $CARGO_HOME
        fingerprint_script: cat Cargo.lock
    build_script: cargo build --verbose
    test_script: cargo test
