container:
    image: rust:latest

test_task:
    cargo_cache:
        folder: $CARGO_HOME
        fingerprint_script: cat Cargo.lock
    target_cache:
        folder: target
        fingerprint_script: cat Cargo.lock
    build_script: cargo build --verbose
    test_script: cargo test
    before_cache_script:
      - rm target/.rustc_info.json
      - rm -rf target/debug/incremental
      - find target/ -name "*${CIRRUS_REPO_NAME//-/_}*" -type f -delete
      - find target/ -name "*${CIRRUS_REPO_NAME//-/_}*" -type d -exec rm -rf {} +
      - find target/ -name "*$CIRRUS_REPO_NAME*" -type d -exec rm -rf {} +
      - find target/ -name "*$CIRRUS_REPO_NAME*" -type f -delete
