container:
    image: rust:latest

test_task:
    printenv_script: printenv
    cargo_home_cache:
        folder: ~/.cargo
        fingerprint_script: cat Cargo.lock
    cargo_cache:
        folder: target
        fingerprint_script: cat Cargo.lock
    build_script: cargo build --verbose
    test_script: cargo test
